# This YAML configuration file defines the generalists experiment search space.
# All values provided in a list expand the search space.
#
# For example, if model_name is ["convtasnet", "grunet"] and batch_size is
# [32, 64, 128], then there are six experiments total. As another example, if
# model_name and batch_size are defined as before, and distance_func is
# [0.001, 0.01, 0.1] and distance_func is ['snr', 'mse'], then there would
# be thirty-six experiments total to run.

# -----------------------------------------------------------------------------
# ray configuration
# -----------------------------------------------------------------------------
available_devices: '4,5,6,7'  # (these should be GPU IDs, check `nvidia-smi`)
num_gpus_per_experiment: 0.5
num_cpus_per_experiment: 0.5
output_folder: "~/ray_results/"

# -----------------------------------------------------------------------------
# data configuration
# -----------------------------------------------------------------------------
folder_librispeech: "/data/asivara/librispeech/"
folder_musan: "/data/asivara/musan/"

sample_rate: 16000
example_duration: 4  # (in seconds)

batch_size:  # (should be specified based on available GPU memory)
    - 64

# -----------------------------------------------------------------------------
# model configuration
# -----------------------------------------------------------------------------
model_name:  # (choices: "convtasnet", "grunet")
    - 'convtasnet'
    # - 'grunet'

model_size:  # (choices: "tiny", "small", "medium", "large")
    - 'tiny'
    - 'small'
    - 'medium'
    - 'large'

learning_rate:
    - 0.001

distance_func:  # (distance function used to compare estimate & target signals)
    - 'snr'
    # - 'sisdr'
    # - 'mse'